import asyncio
import re
import shutil
import sys

import config
from agent import run_agent
from asana_client import add_comment, assign_task, get_unassigned_tasks
from github_client import clone_repo, commit_and_push, create_branch, create_pr, get_repo_summary
from prompts.task_prompt import build_agent_prompt
from task_selector import select_task


def _branch_name(task: dict, prefix: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", task["name"].lower()).strip("-")[:40]
    return f"{prefix}asana-{task['gid']}-{slug}"


async def run(dry_run: bool = False) -> None:
    all_tasks = []
    task_project_map: dict[str, dict] = {}  # task gid -> project config
    repo_summaries: list[str] = []
    for project in config.PROJECTS:
        print(f"Fetching tasks from project: {project['asana_project_id']}")
        fetched = get_unassigned_tasks(project["asana_project_id"])
        all_tasks.extend(fetched)
        for t in fetched:
            task_project_map[t["gid"]] = project
        print(f"Fetching repo summary for {project['github_repo']}")
        repo_summaries.append(get_repo_summary(project["github_repo"]))

    repo_context = "\n\n---\n\n".join(repo_summaries)
    task = await select_task(all_tasks, repo_context=repo_context)
    if task is None:
        print("No feasible task found. Exiting.")
        return

    print(f"Selected task: [{task['gid']}] {task['name']}")

    if dry_run:
        print("[dry-run] Would assign, clone, implement, and open PR. Exiting.")
        return

    project_cfg = task_project_map[task["gid"]]
    repo = project_cfg["github_repo"]
    branch = _branch_name(task, project_cfg["branch_prefix"])

    assign_task(task["gid"], config.ASANA_ASSIGNEE_GID)
    add_comment(
        task["gid"],
        f"I'm picking this up. Proposed approach: I'll analyse the codebase and implement a fix on branch `{branch}`. Will post the PR link here once done.",
    )

    repo_path = clone_repo(repo)
    try:
        create_branch(repo_path, branch)
        prompt = build_agent_prompt(task, repo)
        result = await run_agent(repo_path, prompt)

        if not result.success:
            assign_task(task["gid"], None)  # unassign
            add_comment(
                task["gid"],
                f"I ran into an error and could not complete this task:\n\n{result.error}",
            )
            return

        commit_and_push(repo_path, branch, f"fix: {task['name'][:72]}")
        pr_url = create_pr(
            repo=repo,
            branch=branch,
            title=task["name"][:72],
            body=f"## Summary\n\n{result.summary}\n\n**Asana task:** https://app.asana.com/0/0/{task['gid']}\n\n---\n_AI-generated by sweat agent_",
        )
        add_comment(task["gid"], f"PR opened: {pr_url}")
        print(f"Done. PR: {pr_url}")
    finally:
        shutil.rmtree(repo_path, ignore_errors=True)


if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    asyncio.run(run(dry_run=dry_run))
